# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36

sites:
  - name: Web - urlBank
    url: https://urlbank.interio-inc.com/
  - name: Web - timeStamp
    url: https://tsv2.interio-inc.com/sign-in
  - name: Web - www.kokono.cloud
    url: https://www.kokono.cloud/
  - name: Web - specify (kokono pro )
    url: https://specify.kokono.cloud/
  - name: Web - kokono lite
    url: https://app.kokono.cloud/
  - name: Web - cv maker App
    url: https://cvapp.kokono.cloud/
  - name: Web - cv maker landing ( CloudFlare )
    url: https://cv.kokono.cloud/
    # cloudFlare
  - name: Web - chintaiKing
    url: http://king.kokono.cloud/
  - name: Web - Interio  ( CloudFlare )
    url: https://www.interio-inc.com/
    # cloudFlare
  - name: Web - town.kokono
    url: https://town.kokono.cloud/
  - name: Web - town Admin
    url: https://town-admin.kokono.cloud/
  - name: API - town-kokono
    url: https://api-town-admin.kokono.cloud/health
  - name: API - cv-kokono
    url: https://prod-cv-api.kokono.cloud/api/test/health
  - name: API - kokono-lite
    url: https://api.kokono.cloud/ping
  - name: API - kokono-pro
    url: https://spec-api.interio-inc.com/ping    
  - name: API - king.kokono
    url: https://api-king.kokono.cloud/health
  - name: API - urlBank
    url: https://urlbank_api.intterio-inc.com/health
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
